# Generated by Django 6.0.5 on 2026-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopperProfile',
            fields=[
                ('shopper_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('sticker_balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
