# Generated by Django 6.0.5 on 2026-06-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopper_id', models.CharField(db_index=True, max_length=255)),
                ('reward_id', models.CharField(max_length=64)),
                ('reward_name', models.CharField(max_length=255)),
                ('stickers_cost', models.IntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
