services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: interview
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/.venv
      - /app/node_modules
      - /app/staticfiles
      - /app/bundled_assets
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  webpack:
    build: .
    command: npm run watch
    volumes:
      - .:/app
      - /app/.venv
      - /app/node_modules
      - /app/staticfiles
      - /app/bundled_assets
    profiles:
      - dev

volumes:
  postgres_data:
  redis_data:
