# Generated by Django 6.0.5 on 2026-06-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('shopper_id', models.CharField(db_index=True, max_length=255)),
                ('store_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('items', models.JSONField()),
                ('basket_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stickers_earned', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AppliedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=64)),
                ('offer_type', models.CharField(max_length=64)),
                ('offer_name', models.CharField(max_length=255)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stickers_earned', models.IntegerField(default=0)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_offers', to='transactions.transaction')),
            ],
        ),
    ]
