# Generated by Django 6.0.5 on 2026-06-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='processed_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
