/* eslint-env node */
const fs = require("fs")
const path = require("path");
const settings = require("./settings");;

const fetchJsonDataOrDefault = (filePath, defaultData) =>
    fs.existsSync(filePath)
        ? JSON.parse(fs.readFileSync(filePath, "utf-8"))
        : defaultData;

// Note: This file is generated by js_entry/build.js and should be part of the npm
// build process. It is not meant to be manually edited.
const DETAILS = fetchJsonDataOrDefault(settings.DETAILS_PATH, {});

/**
 * Returns the full path to an application's assets folder.
 * eg /path/to/looplink/base/assets
 *
 * @type {string}
 */
const getAssetsFolderForApp = appName => {
    const appPath = DETAILS.allAppPaths[appName];
    if (!appPath) {
        console.warn(`No path found for ${appName}`);
    }
    return path.join(appPath, settings.ASSETS_DIR);
};


/**
 * A quick utility for generating full paths to directories within
 * an app's static folder.
 *
 * Given an appName like `base` and a directory like `htmx`,
 * this returns the full path to that directory
 * /path/to/looplink/base/assets/htmx
 *
 * @type {string}
 */
const getAssetPathForApp = (appName, directory = "") => {
    const assetsFolder = getAssetsFolderForApp(appName);
    return path.resolve(assetsFolder, appName, directory);
};

/**
 * Entries in Webpack are also referred to as "modules". These
 * entries are determined by the `js_entry` or template
 * tags in `ll_tags.py`
 *
 * For instance, {% js_entry `base/common_entry` %}
 * Where the entry then looks something like:
 * ```
 * "base/common_entry": {
 *     import: '/path/to/looplink/base/assets/common_entry.js',
 *     // the path of the output file that will live in `staticfiles/webpack`
 *     filename: 'base/common_entry.js`,
 * }
 * ```
 *
 */
const getEntries = () => DETAILS.entries;

const getAllAliases = aliases => ({ ...aliases, ...DETAILS.aliases });

/**
 * Cache Groups are effectively parent "modules" containing shared code
 * amongst the generated entries. There is a common chunk to contain the most widely
 * shared code across the codebase, a vendor chunk which includes code from npm dependencies
 * that changes less frequently than code within the codebase. Lastly, there are chunks
 * for commonly shared code (if needed, based on size requirements) within each app.
 *
 * Cache Groups are "modules" of shared code across different entries that can be
 * cached by the browser so the unique code for a particular entry point can be condensed.
 * Subsequent loads of pages within looplink or pages within a particular app of looplink can rely
 * on reading the cache of this common code rather than requesting an enormous entry
 * point file each time.
 *
 * See Webpack's documentation to learn more about Code Splitting and Cache Groups:
 * https://webpack.js.org/plugins/split-chunks-plugin/
 *
 * @type {dict} - a dict of cache group definitions
 */
const getCacheGroups = () => {
    const cacheGroups = {
        common: {
            name: "common",
            chunks: "all",
            minChunks: 2,
            priority: 2, // if two cache groups might share a module, prioritize loading into common
        },
        vendor: {
            test: /[\\/]node_modules[\\/]/,
            name: "vendor",
            chunks: "all",
            priority: 2,
        },
        styles: {
            name: "styles",
            type: "css/mini-extract",
            chunks: "all",
            enforce: true,
        },
    };

    DETAILS.appsWithEntries.forEach(appName => {
        const testExp = new RegExp(`[\\\\/]${appName}[\\\\/]js[\\\\/]`);
        cacheGroups[appName] = {
            test: testExp,
            name: `${appName}/${appName}.bundle`,
            chunks: "all",
            minChunks: 1,
            // core/utils shares the highest priority among the modules
            // as it is the most shared module across the codebase
            // and should be loaded first before any other modules
            // that are shared between apps
            priority: appName === settings.BASE_APP_NAME ? 1 : 0,
        };
    });
    return cacheGroups;
};

module.exports = {
    getAssetsFolderForApp,
    getAssetPathForApp,
    getEntries,
    getAllAliases,
    getCacheGroups,
};
